-- Migration 00040: Grants Pipeline (Grant Writing MVP)
--
-- Context: Grant writing MVP (feat/grant-writing-mvp). Creates the
-- grants_pipeline table that tracks each grant an org is pursuing through
-- the full lifecycle from discovery to decision.
--
-- Schema per PRD-grant-writing-capability-2026-05-10.md §F2.
-- RLS pattern matches members table: SECURITY DEFINER helper
-- `public.current_user_org_ids()` (defined in 00028_fix_members_rls_recursion.sql)
-- bypasses recursion that plagues direct `members` joins in policies.
--
-- Manual apply: run this file in the Supabase SQL Editor (Citlali).
-- Same workflow as 00033/00036/00037/00038.
-- DO NOT apply in prod until feat/grant-writing-mvp is merged to main.

-- ---------------------------------------------------------------------------
-- 1. Extend memory_entries category constraint (grant_writing.* namespaces)
-- ---------------------------------------------------------------------------
-- Adds new grant-writing overlay categories that `save_to_memory` will
-- accept and `draft_grant_content` handler will pull at draft time.
-- The existing constraint drop+recreate pattern matches 00038.

ALTER TABLE public.memory_entries DROP CONSTRAINT IF EXISTS memory_entries_category_check;

ALTER TABLE public.memory_entries ADD CONSTRAINT memory_entries_category_check
  CHECK (category IN (
    'mission', 'programs', 'donors', 'grants', 'campaigns',
    'brand_voice', 'contacts', 'processes', 'general',
    'financials', 'volunteers', 'events',
    'org_profile',          -- Sprint A: org context preamble
    'outcomes',             -- Sprint A.5: quantitative impact data
    'prior_grants',         -- Sprint A.5: historical grant awards/applications
    'voice_samples',        -- Sprint A.5: org communication voice/style samples
    'grant_writing.tone_rules',              -- Grant writing MVP: hard tone constraints
    'grant_writing.style_samples',           -- Grant writing MVP: voice training samples
    'grant_writing.preferred_section_lengths', -- Grant writing MVP: section word counts
    'grant_writing.signatory_default',       -- Grant writing MVP: cover letter ED name+title
    'grant_writing.indirect_rate_default',   -- Grant writing MVP: budget narrative indirect rate
    'grant_writing_artifact'                 -- Grant writing MVP: past LOIs/proposals
  ));

-- ---------------------------------------------------------------------------
-- 2. Create grants_pipeline table
-- ---------------------------------------------------------------------------

CREATE TABLE public.grants_pipeline (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,

  -- Source-system identity
  grant_id text NOT NULL,         -- Grants.gov OPP-ID, ProPublica EIN, etc.
  source text NOT NULL,           -- 'grants_gov' | 'propublica' | 'givingtuesday' | etc.

  -- Grant details
  funder_name text NOT NULL,
  opportunity_title text NOT NULL,
  amount_min integer,             -- nullable; in dollars (not cents per PRD intent)
  amount_max integer,
  due_date date,
  citation_url text NOT NULL,
  org_fit_score integer,          -- Sonnet judge score 0-100 from find_grants_for_org

  -- Pipeline state
  status text NOT NULL DEFAULT 'discovered'
    CONSTRAINT grants_pipeline_status_check CHECK (status IN (
      'discovered', 'verification', 'drafting',
      'internal_review', 'submitted', 'won', 'lost', 'withdrawn'
    )),

  -- Content
  -- drafts: append-only array of { section, content_md, version, drafted_at, drafted_by_tool }
  drafts jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- attachments_checklist: generated by compile_application (v2)
  attachments_checklist jsonb,
  notes text,

  -- Audit
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  created_by uuid REFERENCES public.members(id),

  -- Dedup: same grant from same source deduplicated; same grant from different
  -- sources gets separate rows (distinct discovery provenance).
  UNIQUE (org_id, grant_id, source)
);

-- ---------------------------------------------------------------------------
-- 3. RLS — SECURITY DEFINER pattern from 00028
-- ---------------------------------------------------------------------------

ALTER TABLE public.grants_pipeline ENABLE ROW LEVEL SECURITY;

CREATE POLICY grants_pipeline_select ON public.grants_pipeline
  FOR SELECT USING (org_id IN (SELECT public.current_user_org_ids()));

CREATE POLICY grants_pipeline_insert ON public.grants_pipeline
  FOR INSERT WITH CHECK (org_id IN (SELECT public.current_user_org_ids()));

CREATE POLICY grants_pipeline_update ON public.grants_pipeline
  FOR UPDATE USING (org_id IN (SELECT public.current_user_org_ids()));

CREATE POLICY grants_pipeline_delete ON public.grants_pipeline
  FOR DELETE USING (org_id IN (SELECT public.current_user_org_ids()));

-- ---------------------------------------------------------------------------
-- 4. Indexes
-- ---------------------------------------------------------------------------

-- Primary access pattern: list pipeline by org + status
CREATE INDEX idx_grants_pipeline_org_status
  ON public.grants_pipeline (org_id, status);

-- Deadline sorting: active grants (excludes decided column)
CREATE INDEX idx_grants_pipeline_due
  ON public.grants_pipeline (due_date)
  WHERE status NOT IN ('won', 'lost', 'withdrawn');

-- updated_at for cache busting / ordering
CREATE INDEX idx_grants_pipeline_updated
  ON public.grants_pipeline (org_id, updated_at DESC);

-- ---------------------------------------------------------------------------
-- 5. updated_at auto-trigger (same pattern as other tables in this schema)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_grants_pipeline_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER grants_pipeline_set_updated_at
  BEFORE UPDATE ON public.grants_pipeline
  FOR EACH ROW EXECUTE FUNCTION public.set_grants_pipeline_updated_at();
